In [14]:
import pandas as pd
import locale

locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8') # locale - Brasil

'pt_BR.UTF-8'

In [17]:
print(df.columns)

Index(['USUÁRIO', 'E-MAIL', 'CPF', '# RELATÓRIO', 'TIME', 'CATEGORIA',
       'SUBCATEGORIA', 'PROJETO', 'DESCRIÇÃO', 'DATA DA DESPESA', 'MOEDA',
       'VALOR', 'NÃO REEMBOLSÁVEL', 'CARTÃO', 'STATUS', 'DATA DE ENVIO',
       'DATA DE APROVAÇÃO', 'APROVADORES', 'DATA DE CONCLUSÃO', 'CONCLUIDORES',
       'URL DO COMPROVANTE', 'URL DO RELATÓRIO', 'MOTIVO 1', 'MOTIVO 2',
       'MOTIVO 3', 'MOTIVO 4'],
      dtype='object')

In [ ]:
df = pd.read_excel(r"C:\Users\Projexa\OneDrive - projexa.com.br\Área de Trabalho\Estudos_python\1.Dashboard_reembolso_projetos\data\05-03-2026 15_47_21.xlsx")
df.head(2)

,USUÁRIO,E-MAIL,CPF,# RELATÓRIO,TIME,CATEGORIA,SUBCATEGORIA,PROJETO,DESCRIÇÃO,DATA DA DESPESA,...,DATA DE APROVAÇÃO,APROVADORES,DATA DE CONCLUSÃO,CONCLUIDORES,URL DO COMPROVANTE,URL DO RELATÓRIO,MOTIVO 1,MOTIVO 2,MOTIVO 3,MOTIVO 4
0,Robinson Lucas,439658213963desativado.robinson.lucas@projexa....,NaN,42,Projexa Colaboradores,Alimentação,Almoço,PE554 - INTEC (BRACELL),Almoço,25/01/2021,...,24/03/2021,Paulo Souza; Marcia Baldin; Luis Filipe de Sou...,13/04/2021,Adriana Souza,https://s3-sa-east-1.amazonaws.com/espressoapp...,https://app.espressoapp.com.br/reports/af7a02d...,01 - Campo,NaN,NaN,NaN
1,Robinson Lucas,439658213963desativado.robinson.lucas@projexa....,NaN,42,Projexa Colaboradores,Alimentação,Jantar,PE554 - INTEC (BRACELL),Janta,25/01/2021,...,24/03/2021,Paulo Souza; Marcia Baldin; Luis Filipe de Sou...,13/04/2021,Adriana Souza,https://s3-sa-east-1.amazonaws.com/espressoapp...,https://app.espressoapp.com.br/reports/af7a02d...,01 - Campo,NaN,NaN,NaN

In [ ]:
# 1 - EXCLUI COLUNAS DESNECESSÁRIAS
df1 = df.drop(['E-MAIL', 'CPF', 'TIME', 'MOEDA', 'NÃO REEMBOLSÁVEL','DATA DE ENVIO', 
               'DATA DE CONCLUSÃO', 'CONCLUIDORES', 
               'URL DO COMPROVANTE', 'URL DO RELATÓRIO', 'MOTIVO 1', 
               'MOTIVO 2','MOTIVO 3', 'MOTIVO 4'], axis=1)

# 2 - CORREÇÃO DE NOME COLUNA
df2 = df1.rename(columns={'# RELATÓRIO':'RELATÓRIO', 'DATA DA DESPESA':'MES_ANO'})

# 3 - REORGANIZAÇÃO DAS CONLUNAS
df3 = df2[['RELATÓRIO','USUÁRIO','MES_ANO','VALOR','CATEGORIA','SUBCATEGORIA','PROJETO','DESCRIÇÃO','APROVADORES']]
df3

,RELATÓRIO,USUÁRIO,MES_ANO,VALOR,CATEGORIA,SUBCATEGORIA,PROJETO,DESCRIÇÃO,APROVADORES
0,42,Robinson Lucas,25/01/2021,23.00,Alimentação,Almoço,PE554 - INTEC (BRACELL),Almoço,Paulo Souza; Marcia Baldin; Luis Filipe de Sou...
1,42,Robinson Lucas,25/01/2021,38.00,Alimentação,Jantar,PE554 - INTEC (BRACELL),Janta,Paulo Souza; Marcia Baldin; Luis Filipe de Sou...
2,42,Robinson Lucas,20/01/2021,220.00,Outros,Material ou Suprimento (CUSTO CLIENTE - OBRIGA...,PE554 - INTEC (BRACELL),Teste Covid19,Paulo Souza; Marcia Baldin; Luis Filipe de Sou...
3,42,Robinson Lucas,26/01/2021,34.00,Alimentação,Jantar,PE554 - INTEC (BRACELL),Janta,Paulo Souza; Marcia Baldin; Luis Filipe de Sou...
4,42,Robinson Lucas,27/01/2021,142.37,Transporte,Combustível,PE554 - INTEC (BRACELL),Abastecimento,Paulo Souza; Marcia Baldin; Luis Filipe de Sou...
...,...,...,...,...,...,...,...,...,...
44251,3613,Guilherme de Lima Silva,18/03/2025,35.00,Alimentação,Almoço,PE782.12-EDP-ES-Remodelagem SD Montanha-2024,Almoço,Yasmin Luna Dru Dias; Marcia Baldin
44252,3613,Guilherme de Lima Silva,19/03/2025,35.00,Alimentação,Almoço,PE782.12-EDP-ES-Remodelagem SD Montanha-2024,Almoço,Yasmin Luna Dru Dias; Marcia Baldin
44253,3614,Guilherme de Lima Silva,20/03/2025,35.00,Alimentação,Almoço,PE782.08 -EDP-ES-Remodelagem SD Linhares-2024,Almoço,Yasmin Luna Dru Dias; Marcia Baldin
44254,3614,Guilherme de Lima Silva,21/03/2025,35.00,Alimentação,Almoço,PE782.08 -EDP-ES-Remodelagem SD Linhares-2024,Almoço,Yasmin Luna Dru Dias; Marcia Baldin
44255,3613,Guilherme de Lima Silva,21/03/2025,245.00,Alimentação,Jantar,PE782.12-EDP-ES-Remodelagem SD Montanha-2024,Referente ao jantar dos dias 15/03 - 21/03,Yasmin Luna Dru Dias; Marcia Baldin